### ISSUE TITLE
API appears to be offline

### ISSUE THREAD

**Issue by cameronhunter** [amonks/oblique-strategies-api#1]
I'm seeing Application Error on all endpoints of the API. Is it still available?

**Comment by amonks** [comment]
Oof, sorry.

You should be good to go now.

* * *

I made this before heroku started limiting free dyno hours.

I just switched it onto a hobby dyno for the time being, and I'll figure out something cheaper/static going forward.

**Comment by amonks** [comment]
just curious: what specifically are you using the API for?

**Comment by cameronhunter** [comment]
I was throwing together an Alexa Skill: https://github.com/cameronhunter/oblique-strategies-alexa-skill

**Comment by amonks** [comment]
cool!
